import { useNavigate } from "react-router-dom";
import DashboardLayout from "../../components/DashboardLayout";
import { clearAuthentication, getStoredRole } from "../../utils/authStorage";
import { getCurrentUser } from "../../utils/getCurrentUser";
import "../../styles/Profile.css";

function normalizeRole(role) { return String(role || "").trim().toLowerCase().replaceAll("_", " ").replaceAll("-", " "); }
function getDashboardPath(role) { switch (normalizeRole(role)) { case "admin": return "/admin-dashboard"; case "manager": return "/manager-dashboard"; case "it support agent": case "agent": case "it": return "/agent-dashboard"; case "employee": return "/employee-dashboard"; default: return "/login"; } }
function getInitials(name) { return String(name || "User").split(" ").filter(Boolean).map((part) => part[0]).slice(0, 2).join("").toUpperCase(); }

function Profile() {
  const navigate = useNavigate();
  const currentUser = getCurrentUser();
  const role = getStoredRole() || "User";
  const dashboardPath = getDashboardPath(role);
  function handleLogout() { clearAuthentication(); sessionStorage.removeItem("resetEmail"); sessionStorage.removeItem("passwordResetToken"); navigate("/login", { replace: true }); }
  return <DashboardLayout activePage="profile"><main className="profile-page"><header className="profile-page-header"><div><span className="profile-eyebrow">Account</span><h1>My Profile</h1><p>Your SupportHub identity, role and account access in one place.</p></div><button type="button" className="profile-dashboard-button" onClick={() => navigate(dashboardPath)}>Back to Dashboard</button></header><section className="profile-hero-card"><div className="profile-avatar-large">{getInitials(currentUser?.name)}</div><div className="profile-hero-copy"><span className="profile-role-pill">{role}</span><h2>{currentUser?.name || "SupportHub User"}</h2><p>{currentUser?.email || "No email available"}</p></div><div className="profile-account-state"><span className="profile-status-dot" /><div><small>Account status</small><strong>Active</strong></div></div></section><section className="profile-content-grid"><article className="profile-card"><div className="profile-card-heading"><div><span>Personal details</span><h2>Account Information</h2></div></div><div className="profile-info-list"><div className="profile-info-row"><span>Full name</span><strong>{currentUser?.name || "—"}</strong></div><div className="profile-info-row"><span>Email address</span><strong>{currentUser?.email || "—"}</strong></div><div className="profile-info-row"><span>Role</span><strong>{role}</strong></div><div className="profile-info-row"><span>User ID</span><strong>{currentUser?.id || "—"}</strong></div></div></article><article className="profile-card"><div className="profile-card-heading"><div><span>Security</span><h2>Sign-in & Recovery</h2></div></div><div className="profile-security-item"><div><strong>Account password</strong><p>Use the recovery flow whenever your sign-in password needs to be changed.</p></div><button type="button" onClick={() => navigate("/forgot-password")}>Reset Password</button></div><div className="profile-security-item"><div><strong>Recovery verification</strong><p>Phone verification is being prepared for account recovery.</p></div><span className="profile-coming-soon">Coming soon</span></div></article><article className="profile-card profile-quick-card"><div className="profile-card-heading"><div><span>Shortcuts</span><h2>Quick Access</h2></div></div><div className="profile-quick-actions"><button type="button" onClick={() => navigate(dashboardPath)}><strong>Dashboard</strong><span>Return to your workspace →</span></button><button type="button" onClick={() => navigate("/notifications")}><strong>Notifications</strong><span>Review your latest updates →</span></button></div></article><article className="profile-card profile-session-card"><div className="profile-card-heading"><div><span>Session</span><h2>Account Session</h2></div></div><p>Sign out of this browser when you are finished using SupportHub.</p><button type="button" className="profile-logout-button" onClick={handleLogout}>Log Out</button></article></section></main></DashboardLayout>;
}
export default Profile;
