import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import DashboardLayout from "../../components/DashboardLayout";
import {
  addInternalNote, addTicketComment, addManagerTicketComment, uploadCommentAttachments, assignTicket, cancelTicket,
  closeTicket, editTicket, escalateTicket, getAssignmentOptions, getInternalNotes,
  getTicketActivity, getTicketAttachments, getTicketById, getTicketComments, getTicketHistory,
  managerReopenTicket, pauseWork, resolveTicket, returnTicketToManager, startWork, getAttachmentBlobUrl,
} from "../../api/ticket";
import "../../styles/Tickets.css";

const normalize=v=>String(v||"").trim().toLowerCase().replaceAll("_"," ").replaceAll("-"," ");
const badge=v=>normalize(v).replaceAll(" ","-");
const initials=v=>String(v||"NA").trim().split(/\s+/).map(p=>p[0]).join("").slice(0,2).toUpperCase();
const role=()=>normalize(localStorage.getItem("role")||sessionStorage.getItem("role"));
const author=c=>c.author?.name||c.user?.name||c.userName||c.authorName||"User";
function date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString([],{month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"});}
function bytes(v){const n=Number(v||0);return n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`;}

function Attachment({ticketId,item,compact=false}){
  const[busy,setBusy]=useState(false);
  async function open(){setBusy(true);try{const url=await getAttachmentBlobUrl(ticketId,item.id);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){window.alert(e.message);}finally{setBusy(false);}}
  if(compact)return <button className="ticket-comment-attachment" type="button" onClick={open} disabled={busy}><span>{busy?"Opening…":item.fileName}</span></button>;
  return <button className="ticket-file-card" type="button" onClick={open} disabled={busy}><span className="ticket-file-preview">{item.contentType?.startsWith("image/")?"IMG":"FILE"}</span><span className="ticket-file-meta"><strong>{item.fileName}</strong><span>{bytes(item.fileSize)} · {date(item.uploadedAt)}</span></span><span className="ticket-file-open">{busy?"Opening…":"Open"}</span></button>;
}
function AttachmentList({ticketId,items=[]}){return items.length?<div className="ticket-comment-attachments">{items.map(x=><Attachment key={x.id} ticketId={ticketId} item={x} compact/>)}</div>:null;}
function FileChips({files,setFiles}){return files.length?<div className="ticket-comment-files">{files.map((f,i)=><div className="ticket-comment-file" key={`${f.name}-${i}`}><span>{f.name}</span><button type="button" onClick={()=>setFiles(a=>a.filter((_,n)=>n!==i))}>×</button></div>)}</div>:null;}

export default function TicketDetails(){
 const{id}=useParams();const navigate=useNavigate();const userRole=role();
 const isManager=userRole==="manager",isAdmin=userRole==="admin",isEmployee=userRole==="employee",isAgent=["agent","it support agent"].includes(userRole);
 const[ticket,setTicket]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[comments,setComments]=useState([]),[notes,setNotes]=useState([]),[activity,setActivity]=useState([]),[history,setHistory]=useState([]),[attachments,setAttachments]=useState([]),[agents,setAgents]=useState([]);
 const[selectedAgent,setSelectedAgent]=useState(""),[working,setWorking]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[tone,setTone]=useState("success");
 const[comment,setComment]=useState(""),[commentFiles,setCommentFiles]=useState([]),[replyTo,setReplyTo]=useState(null),[note,setNote]=useState(""),[noteFiles,setNoteFiles]=useState([]);
 const[action,setAction]=useState(""),[actionNote,setActionNote]=useState(""),[stopChoice,setStopChoice]=useState("no-issue"),[historyOpen,setHistoryOpen]=useState(false),[editOpen,setEditOpen]=useState(false),[editForm,setEditForm]=useState({subject:"",description:"",category:"",priority:"",reason:""});
 const sortedAgents=useMemo(()=>[...agents].sort((a,b)=>Number(a.activeTickets||0)-Number(b.activeTickets||0)||String(a.name).localeCompare(String(b.name))),[agents]);const leastBusy=sortedAgents[0];
 const status=normalize(ticket?.status),isResolved=status==="resolved",isClosed=status==="closed",isCancelled=["cancelled","canceled"].includes(status),readOnly=isClosed||isCancelled;
 const timeline=useMemo(()=>[...activity.map(x=>({...x,kind:"Activity",at:x.createdAt})),...history.map(x=>({...x,kind:"History",at:x.createdAt}))].sort((a,b)=>new Date(b.at||0)-new Date(a.at||0)),[activity,history]);
 const roots=comments.filter(c=>!c.parentCommentID),replies=parentId=>comments.filter(c=>Number(c.parentCommentID)===Number(parentId));
 const canPublicComment=isEmployee||isAgent||isManager;
 async function load(){setLoading(true);setError("");try{const[t,c,a]=await Promise.all([getTicketById(id),getTicketComments(id),getTicketAttachments(id)]);setTicket(t);setWorking(Boolean(t.activeWorkSession));setComments(c);setAttachments(a);if(isManager){const opts=await getAssignmentOptions();setAgents(opts.agents||[]);}if(!isEmployee){try{setActivity(await getTicketActivity(id));}catch{setActivity([]);}try{setNotes(await getInternalNotes(id));}catch{setNotes([]);}}if(isManager||isAdmin){try{setHistory(await getTicketHistory(id));}catch{setHistory([]);}}}catch(e){setError(e.message||"The ticket could not be loaded.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[id]);
 useEffect(()=>{if(!isManager)return;if(ticket?.assignedAgent?.id)setSelectedAgent(String(ticket.assignedAgent.id));else if(!selectedAgent&&leastBusy)setSelectedAgent(String(leastBusy.id));},[ticket,leastBusy,isManager]);
 async function refreshConversation(){setComments(await getTicketComments(id));setAttachments(await getTicketAttachments(id));if(!isEmployee)try{setNotes(await getInternalNotes(id));}catch{}}
 async function doWork(){setBusy(true);try{const r=working?await pauseWork(id):await startWork(id);setMessage(r.message||"Work session updated.");setTone("success");await load();}catch(e){setMessage(e.message);setTone("error");}finally{setBusy(false);}}
 async function assign(agentId){if(!agentId)return;setBusy(true);try{const r=await assignTicket(id,agentId);setMessage(r.message||"Ticket assigned.");setTone("success");await load();}catch(e){setMessage(e.message);setTone("error");}finally{setBusy(false);}}
 async function postComment(e){e.preventDefault();if(!comment.trim())return;setBusy(true);try{const r=isManager?await addManagerTicketComment(id,comment,replyTo):await addTicketComment(id,comment,replyTo);if(commentFiles.length&&r.comment?.id)await uploadCommentAttachments(id,r.comment.id,commentFiles);setComment("");setCommentFiles([]);setReplyTo(null);await refreshConversation();}catch(e2){setMessage(e2.message);setTone("error");}finally{setBusy(false);}}
 async function postNote(e){e.preventDefault();if(!note.trim())return;setBusy(true);try{const r=await addInternalNote(id,note);if(noteFiles.length&&r.note?.id)await uploadCommentAttachments(id,r.note.id,noteFiles);setNote("");setNoteFiles([]);await refreshConversation();}catch(e2){setMessage(e2.message);setTone("error");}finally{setBusy(false);}}
 function openAction(name){setAction(name);setActionNote("");if(name==="stop")setStopChoice("no-issue");}
 async function runAction(){const text=actionNote.trim();if(!text){setMessage("Please add a reason or note first.");setTone("error");return;}setBusy(true);try{let r,leave=false;if(action==="resolve")r=await resolveTicket(id,text);if(action==="escalate"){r=await escalateTicket(id,text);leave=true;}if(action==="close")r=await closeTicket(id,text);if(action==="reopen")r=await managerReopenTicket(id,text);if(action==="stop"&&stopChoice==="no-issue"){r=await cancelTicket(id,text);leave=true;}if(action==="stop"&&stopChoice==="could-not-solve"){r=await returnTicketToManager(id,text);leave=true;}setAction("");if(leave&&isAgent){navigate("/agent-dashboard",{replace:true});return;}setMessage(r?.message||"Ticket updated.");setTone("success");await load();}catch(e){setMessage(e.message);setTone("error");}finally{setBusy(false);}}
 function beginEdit(){setEditForm({subject:ticket.subject||"",description:ticket.description||"",category:ticket.category||"",priority:ticket.priority||"",reason:""});setEditOpen(true);}
 async function saveEdit(){if(!editForm.reason.trim()){setMessage("Please enter a reason for the edit.");setTone("error");return;}setBusy(true);try{const r=await editTicket(id,editForm);setEditOpen(false);setMessage(r.message);setTone("success");await load();}catch(e){setMessage(e.message);setTone("error");}finally{setBusy(false);}}
 if(loading)return <DashboardLayout activePage="tickets"><div className="ticket-details-state">Loading ticket…</div></DashboardLayout>;
 if(error||!ticket)return <DashboardLayout activePage="tickets"><div className="ticket-details-state error"><h2>Could not load ticket</h2><p>{error}</p><button onClick={load}>Try again</button></div></DashboardLayout>;
 const standalone=attachments.filter(a=>!a.ticketCommentId);
 return <DashboardLayout activePage={isAdmin?"admin-tickets":"tickets"}><main className="ticket-details-page">
 <header className="ticket-details-header"><div><button className="ticket-back-button" onClick={()=>navigate(-1)}>← Back</button><span className="ticket-details-number">{ticket.ticketNumber}</span><h1>{ticket.subject}</h1><div className="ticket-details-badges"><span className={`ticket-details-badge priority-${badge(ticket.priority)}`}>{ticket.priority}</span><span className={`ticket-details-badge status-${badge(ticket.status)}`}>{ticket.status}</span></div></div>{isAgent&&!isResolved&&!readOnly&&<button className={working?"ticket-pause-work-button":"ticket-start-work-button"} onClick={doWork} disabled={busy}>{working?"Pause Work":"Start Work"}</button>}</header>
 {message&&<div className={`ticket-work-message ${tone}`}>{message}</div>}
 {(isAgent||isManager||isAdmin)&&<section className="ticket-action-bar ticket-action-bar-clear"><div className="ticket-action-bar-copy"><span>Ticket controls</span><strong>Manage status and review ticket history</strong><small>Only valid actions for this ticket are shown.</small></div><div className="ticket-action-buttons">{(isManager||isAdmin)&&<button className="ticket-toolbar-button" onClick={()=>setHistoryOpen(true)}>View History <span>{timeline.length}</span></button>}{(isManager||isAdmin)&&!readOnly&&<button className="ticket-toolbar-button" onClick={beginEdit}>Edit Ticket</button>}{isAgent&&!isResolved&&!readOnly&&<button className="ticket-toolbar-button" onClick={()=>openAction("resolve")}>Resolve</button>}{isAgent&&!isResolved&&!readOnly&&<button className="ticket-toolbar-button" onClick={()=>openAction("escalate")}>Escalate</button>}{isAgent&&!isResolved&&!readOnly&&<button className="ticket-toolbar-button" onClick={()=>openAction("stop")}>Stop Working</button>}{isAgent&&isResolved&&<button className="ticket-toolbar-button primary" onClick={()=>openAction("close")}>Close Ticket</button>}{(isManager||isAdmin)&&(isResolved||readOnly)&&<button className="ticket-toolbar-button" onClick={()=>openAction("reopen")}>Reopen</button>}</div></section>}
 {isManager&&!isResolved&&!readOnly&&<section className="ticket-manager-assignment-card"><div className="ticket-manager-assignment-heading"><div><span>Manager action</span><h2>{ticket.assignedAgent?"Assignment":"This ticket needs an owner"}</h2><p>Assign manually or choose the least busy available agent.</p></div>{ticket.assignedAgent&&<div className="ticket-current-owner"><small>Current owner</small><strong>{ticket.assignedAgent.name}</strong></div>}</div><div className="ticket-manager-assignment-grid"><div className="ticket-manual-assignment"><span>Manual assignment</span><select value={selectedAgent} onChange={e=>setSelectedAgent(e.target.value)} disabled={busy||!sortedAgents.length}>{sortedAgents.map(a=><option key={a.id} value={a.id}>{a.name} · {a.activeTickets} active</option>)}</select><button onClick={()=>assign(selectedAgent)} disabled={busy||!selectedAgent}>{ticket.assignedAgent?"Reassign Ticket":"Assign Ticket"}</button></div><div className="ticket-smart-assignment"><div><span>✦ Smart assignment</span><strong>{leastBusy?.name||"No agent available"}</strong><p>{leastBusy?`${leastBusy.activeTickets} active ticket${Number(leastBusy.activeTickets)===1?"":"s"}`:"No support agents available."}</p></div><button onClick={()=>assign(leastBusy?.id)} disabled={busy||!leastBusy}>✦ Auto Assign</button></div></div></section>}
 <section className="ticket-details-grid"><article className="ticket-details-main-card"><div className="ticket-details-section-heading"><h2>Issue Description</h2></div><p className="ticket-description">{ticket.description}</p><div className="ticket-information-grid"><div><span>Category</span><strong>{ticket.category}</strong></div><div><span>Priority</span><strong>{ticket.priority}</strong></div><div><span>Status</span><strong>{ticket.status}</strong></div><div><span>Created</span><strong>{date(ticket.createdAt)}</strong></div><div><span>Last Updated</span><strong>{date(ticket.updatedAt)}</strong></div><div><span>Closed</span><strong>{date(ticket.closedAt)}</strong></div></div>{standalone.length>0&&<div className="ticket-ticket-files"><div className="ticket-ticket-files-header"><div><strong>Attachments</strong><span>{standalone.length}</span></div></div><div className="ticket-ticket-files-list">{standalone.map(a=><Attachment key={a.id} ticketId={id} item={a}/>)}</div></div>}</article><aside className="ticket-details-sidebar"><article className="ticket-person-card"><span className="ticket-person-label">Requested by</span><div className="ticket-person-details"><span className="ticket-person-avatar">{initials(ticket.employee?.name)}</span><div><strong>{ticket.employee?.name||"Unknown"}</strong><small>{ticket.employee?.email}</small></div></div></article><article className="ticket-person-card"><span className="ticket-person-label">Assigned agent</span>{ticket.assignedAgent?<div className="ticket-person-details"><span className="ticket-person-avatar agent">{initials(ticket.assignedAgent.name)}</span><div><strong>{ticket.assignedAgent.name}</strong><small>{ticket.assignedAgent.email}</small></div></div>:<p className="ticket-unassigned-text">This ticket is currently unassigned.</p>}</article><article className="ticket-work-card"><h2>Work Session</h2><div className={working?"ticket-work-active":"ticket-work-empty"}><strong>{working?"Work session active":"No active work session"}</strong><p>{working?"Working time is being tracked.":"Real working time is preserved across sessions and assignments."}</p></div><div className="ticket-total-work-time"><span>Total working time</span><strong>{ticket.totalWorkMinutes||0} minutes</strong></div></article></aside></section>
 <section className="ticket-details-bottom-grid ticket-details-bottom-single"><article className="ticket-details-placeholder-card ticket-comments-card"><div className="ticket-bottom-card-heading"><div><span>Conversation</span><h2>Comments & Replies</h2></div><small>{comments.length} comment{comments.length===1?"":"s"}</small></div><div className="ticket-comments-list">{roots.length?roots.map(c=><div className="ticket-comment-item" key={c.id}><span className="ticket-comment-avatar">{initials(author(c))}</span><div className="ticket-comment-body"><div className="ticket-comment-meta"><strong>{author(c)}</strong><time>{date(c.createdAt)}</time></div><p>{c.comment}</p><AttachmentList ticketId={id} items={c.attachments||[]}/>{!readOnly&&canPublicComment&&<button type="button" className="ticket-comment-reply-button" onClick={()=>{setReplyTo(replyTo===c.id?null:c.id);setComment("");}}>Reply</button>}{replyTo===c.id&&!readOnly&&canPublicComment&&<form className="ticket-reply-form" onSubmit={postComment}><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder={`Reply to ${author(c)}...`}/><FileChips files={commentFiles} setFiles={setCommentFiles}/><div className="ticket-reply-actions"><label className="ticket-attach-button">Attach screenshot<input hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{setCommentFiles(a=>[...a,...Array.from(e.target.files||[])]);e.target.value="";}}/></label><button type="button" className="ticket-reply-cancel" onClick={()=>{setReplyTo(null);setComment("");setCommentFiles([]);}}>Cancel</button><button type="submit" disabled={busy||!comment.trim()}>Reply</button></div></form>}{replies(c.id).length>0&&<div className="ticket-comment-replies">{replies(c.id).map(r=><div className="ticket-comment-item reply" key={r.id}><span className="ticket-comment-avatar">{initials(author(r))}</span><div className="ticket-comment-body"><div className="ticket-comment-meta"><strong>{author(r)}</strong><time>{date(r.createdAt)}</time></div><p>{r.comment}</p><AttachmentList ticketId={id} items={r.attachments||[]}/></div></div>)}</div>}</div></div>):<div className="ticket-empty-section"><strong>No comments yet</strong><p>Start the support conversation below.</p></div>}</div>{!readOnly&&canPublicComment&&<form className="ticket-comment-form" onSubmit={postComment}><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a comment..."/><FileChips files={commentFiles} setFiles={setCommentFiles}/><div className="ticket-comment-form-footer"><div><label className="ticket-attach-button">Attach screenshot<input hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{setCommentFiles(a=>[...a,...Array.from(e.target.files||[])]);e.target.value="";}}/></label><small>Visible to the employee, assigned IT agent, and manager.</small></div><button type="submit" disabled={busy||!comment.trim()}>Post Comment</button></div></form>}</article></section>
 {!isEmployee&&<section className="ticket-internal-notes-card"><div className="ticket-bottom-card-heading"><div><span>Support only</span><h2>Internal Notes</h2></div><small>Hidden from employees</small></div><div className="ticket-comments-list">{notes.length?notes.map(n=><div className="ticket-comment-item" key={n.id}><span className="ticket-comment-avatar">{initials(n.author?.name)}</span><div className="ticket-comment-body"><div className="ticket-comment-meta"><strong>{n.author?.name||"Support"}</strong><time>{date(n.createdAt)}</time></div><p>{n.note}</p><AttachmentList ticketId={id} items={n.attachments||[]}/></div></div>):<div className="ticket-empty-section"><strong>No internal notes</strong><p>Private support notes stay hidden from the employee.</p></div>}</div>{!readOnly&&<form className="ticket-comment-form" onSubmit={postNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write a private internal note..."/><FileChips files={noteFiles} setFiles={setNoteFiles}/><div className="ticket-comment-form-footer"><div><label className="ticket-attach-button">Attach screenshot<input hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{setNoteFiles(a=>[...a,...Array.from(e.target.files||[])]);e.target.value="";}}/></label><small>Only IT agents, managers and admins can see this.</small></div><button type="submit" disabled={busy||!note.trim()}>Add Internal Note</button></div></form>}</section>}
 {historyOpen&&(isManager||isAdmin)&&<div className="ticket-action-modal-backdrop" onMouseDown={()=>setHistoryOpen(false)}><section className="ticket-history-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span>Ticket history</span><h3>Activity Timeline</h3><p>Every recorded workflow update for {ticket.ticketNumber}.</p></div><button onClick={()=>setHistoryOpen(false)}>×</button></header><div className="ticket-history-modal-list">{timeline.length?timeline.map((x,i)=><div className="ticket-timeline-item" key={`${x.kind}-${x.id||i}`}><span className="ticket-timeline-dot"/><div className="ticket-timeline-content"><div className="ticket-timeline-meta"><span>{x.kind}</span><time>{date(x.at)}</time></div><strong>{x.description||x.action||x.activityType||"Ticket updated"}</strong>{(x.performedBy?.name||x.changedBy?.name)&&<p>By {x.performedBy?.name||x.changedBy?.name}</p>}</div></div>):<div className="ticket-empty-section">No recorded activity yet.</div>}</div></section></div>}
 {editOpen&&<div className="ticket-action-modal-backdrop"><section className="ticket-action-modal ticket-action-modal-large"><header><div><span>Manager/Admin</span><h3>Edit Ticket</h3></div><button onClick={()=>setEditOpen(false)}>×</button></header><input value={editForm.subject} onChange={e=>setEditForm({...editForm,subject:e.target.value})} placeholder="Subject"/><textarea value={editForm.description} onChange={e=>setEditForm({...editForm,description:e.target.value})} placeholder="Description"/><input value={editForm.category} onChange={e=>setEditForm({...editForm,category:e.target.value})} placeholder="Category"/><input value={editForm.priority} onChange={e=>setEditForm({...editForm,priority:e.target.value})} placeholder="Priority"/><textarea value={editForm.reason} onChange={e=>setEditForm({...editForm,reason:e.target.value})} placeholder="Reason for this edit..."/><footer><button onClick={()=>setEditOpen(false)}>Cancel</button><button className="primary" onClick={saveEdit} disabled={busy}>Save Changes</button></footer></section></div>}
 {action&&<div className="ticket-action-modal-backdrop" onMouseDown={()=>!busy&&setAction("")}><section className="ticket-action-modal ticket-action-modal-large" onMouseDown={e=>e.stopPropagation()}><header><div><span>Confirm action</span><h3>{action==="stop"?"Stop working on this ticket":`${action[0].toUpperCase()}${action.slice(1)} ticket`}</h3></div><button onClick={()=>setAction("")}>×</button></header>{action==="stop"&&<div className="ticket-stop-options"><button className={stopChoice==="no-issue"?"selected":""} onClick={()=>setStopChoice("no-issue")}><strong>No issue found</strong><span>Cancel the ticket.</span></button><button className={stopChoice==="could-not-solve"?"selected":""} onClick={()=>setStopChoice("could-not-solve")}><strong>Could not solve</strong><span>Return it to the manager for reassignment.</span></button></div>}<textarea value={actionNote} onChange={e=>setActionNote(e.target.value)} placeholder={action==="close"?"Closing note…":action==="resolve"?"Resolution notes…":"Reason / notes…"}/><footer><button onClick={()=>setAction("")} disabled={busy}>Back</button><button className="primary" onClick={runAction} disabled={busy}>{busy?"Updating…":"Confirm"}</button></footer></section></div>}
 </main></DashboardLayout>;
}
